### ISSUE TITLE
How do I access the project view? 

### ISSUE THREAD

**Issue by paulycloud** [itsjeffro/deploy#12]
Hi Jeffro. 

I've been scratching my head trying to understand how I can access just the landing page of the projects view. 

I've followed all the instructions listed and published all the assets. I'm using a fresh install of laravel 5.5 with the default routing. I don't see any additional info on how to get the main page to pull up. 

did I miss something? I'd love to get this working. Thanks.

**Comment by itsjeffro** [comment]
Hi @paulkamau2015 You can get to the main dashboard by going to yoursite.com/deploy

Let me know if that helps

**Comment by paulycloud** [comment]
Thank you @itsjeffro. I can access the dashboard!!!! You're awesome. 

I'll work on configuring this and deploying it for my apps. Can't tell you how much i appreciate this. 

Feel free to drop me an email with your PayPal.me info or something.  I'd like to thank you!

**Comment by itsjeffro** [comment]
Cheers @paulkamau2015 no problem and glad it helped.

If you have any issues or have any other questions, let me know :)
