### ISSUE TITLE
Server connection status not confirming

### ISSUE THREAD

**Issue by paulycloud** [itsjeffro/deploy#22]
Hey @itsjeffro 
Got a another for you! 😄 I really wanna get this working. 

For the added server, i took the public key given and added it to my .ssh/authorized_key. The connection status still shows as "connecting" and after refreshing the page, "failed". 

What should the Connect As option be? I set it as "forge" because its what I have on envoyer. 

![image](https://user-images.githubusercontent.com/12877727/84607731-f783a900-ae7c-11ea-9f7b-a71808e8bbb1.png)

Thanks.

**Comment by itsjeffro** [comment]
Hi @paulycloud 
So close :). There should be something in the logs regarding the ssh connection attempt. 

Can you try again and post that?

**Comment by paulycloud** [comment]
Sure. So here's the request load: 

![image](https://user-images.githubusercontent.com/12877727/84675183-e2009480-aef9-11ea-8811-52549f122278.png)

Status code shows as a 204.  There isnt a response to that request

When i try to tail the logs on "/storage/logs/laravel-2020-06-15.log" file, I don't see the requests going out including the failed connection request. 

I only see previous exceptions (like failed queue:restart commands). i'm using the Queue table for my jobs. 

What could i do to generate a useful error log?

**Comment by itsjeffro** [comment]
Hi @paulycloud 

Given that the connection is showing up as "Failed" Indicates that the job was processed which is good.

As for why it's not connecting, you should be get something like the following...

`The command "ssh -p 22 -i /var/www/html/storage/app/keys/5 -o StrictHostKeyChecking=no j<user>@<ip address> " failed.`

But as you mentioned, you haven't received any logs. So we might have to try troubleshooting somethings here.

- Can you provide some information on the server you're running deploy on?
- Is there a private key generated in your /app/keys directory?
- Do you have openssh-clients installed on your server that is running deploy?

In cases like this I would suggest running xdebug and placing a break point in `deploy\src\Processors\ServerConnectionProcessor.php`

Let me know how you go :)

**Comment by paulycloud** [comment]
Hey @itsjeffro 

Sorry for the delay on my part. Work had me swamped the last 2 days. 
**- Can you provide some information on the server you're running deploy on?**
I provisioned the server using Laravel forge. I have SSH access into the box. 
**- Is there a private key generated in your /app/keys directory?**
No. I do not. I added the public key in the deploy dashboard to my /authorized_keys file. Thats it. Should i add it somewhere else? 
**- Do you have openssh-clients installed on your server that is running deploy?**
I don't have openssh-clients installed. 

Let me know if you'd like to jump on a quick screen-share. I definitely wanna get this working. I won't give up on it. 😄

**Comment by itsjeffro** [comment]
Heya @paulycloud thats ok. Work has been pretty busy for me as well.

Sure, a screen share sounds good. I'll be free in 3 hours (5.30 pm sydney time)

Let me know what program you want to use and screen name. As well as a good time for you :)

**Comment by paulycloud** [comment]
Hey @itsjeffro 

I'm in Atlanta, EST time zone. 😋

I am flexible to work with your schedule. We could plan for a Friday night EST or Early Saturday? I can stay up pretty late or wake up early. 

We can use Teams or Google Video. We can set up the details that way so that I don't clog up your issues list here on GitHub 😄

**Comment by itsjeffro** [comment]
Heya @paulycloud 

Early saturday sounds good. Ill try and hit you up on google video.

Ill be up at 8 am in sydney time. So that should be around 6pm your time i think :)

**Comment by paulycloud** [comment]
Oi Mate. 😄

Cool. So 8am AEST Saturday is 6pm Friday EST. I will be ready!! 

Send me an email i'll create the invite!! I'm excited to get this working.

Thanks for everything!

**Comment by paulycloud** [comment]
Thanks @itsjeffro !!! I successfully did my first deployment! :)
