### ISSUE TITLE
Not working with fresh laravel version

### ISSUE THREAD

**Issue by sleepycodernotes** [itsjeffro/deploy#25]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install itsjeffro/deploy v1.1.4
    - Conclusion: don't install itsjeffro/deploy 1.x-dev
    - Conclusion: remove guzzlehttp/guzzle 6.5.5

**Comment by itsjeffro** [comment]
Hi @sleepycodernotes 

Thanks for trying the package. What version of laravel are you using?

Ill try and reproduce the issue and get back to you

Cheers

**Comment by itsjeffro** [comment]
Hi @sleepycodernotes 

I'm assuming you might be using a newer version of laravel, possibly 6+

The highest version this currently supports is 5.8

Closing for now with a plan to release Deploy v2.0 in the future which will support Laravel 6 and 7

**Comment by sleepycodernotes** [comment]
Thanks for reply ;) yep i have latest laravel version
