### ISSUE TITLE
ErrorExceptionDeploy\Jobs\DeployJob when atempting to deploy.

### ISSUE THREAD

**Issue by paulycloud** [itsjeffro/deploy#31]
Hi @itsjeffro 

I'm getting this error everytime I hit deploy: 

ErrorException include(/home/forge/"sitename">/releases/20200620003703/vendor/composer/../laravel/framework/src/Illuminate/Contracts/Database/ModelIdentifier.php): failed to open stream: No such file or directory 

I haven't had a successful run again. 

Can you help?

**Comment by itsjeffro** [comment]
Ill try and reproduce the error today 👍 and get back to you when i can

**Comment by itsjeffro** [comment]
Heya @paulycloud 

Would you also be able to send a full stack trace?

**Comment by paulycloud** [comment]
Oi Mate. 

This happens when I hit deploy. The job fails immediately and it goes into the failed_jobs table. 

Here you go: 

ErrorException include(/home/forge/"siteaddress"/releases/20200620003703/vendor/composer/../laravel/framework/src/Illuminate/Contracts/Database/ModelIdentifier.php): failed to open stream: No such file or directory 
    vendor/composer/ClassLoader.php:444 Illuminate\Foundation\Bootstrap\HandleExceptions::handleError
    vendor/composer/ClassLoader.php:444 include
    vendor/composer/ClassLoader.php:444 Composer\Autoload\includeFile
    vendor/composer/ClassLoader.php:322 Composer\Autoload\ClassLoader::loadClass
    [internal] spl_autoload_call
    [internal] unserialize
    vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php:144 Illuminate\Queue\CallQueuedHandler::failed
    vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php:203 Illuminate\Queue\Jobs\Job::failed
    vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php:182 Illuminate\Queue\Jobs\Job::fail
    vendor/laravel/framework/src/Illuminate/Queue/Worker.php:451 Illuminate\Queue\Worker::failJob
    vendor/laravel/framework/src/Illuminate/Queue/Worker.php:438 Illuminate\Queue\Worker::markJobAsFailedIfWillExceedMaxAttempts
    vendor/laravel/framework/src/Illuminate/Queue/Worker.php:368 Illuminate\Queue\Worker::handleJobException
    vendor/laravel/framework/src/Illuminate/Queue/Worker.php:341 Illuminate\Queue\Worker::process
    vendor/laravel/framework/src/Illuminate/Queue/Worker.php:283 Illuminate\Queue\Worker::runJob
    vendor/laravel/framework/src/Illuminate/Queue/Worker.php:118 Illuminate\Queue\Worker::daemon
    vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php:102 Illuminate\Queue\Console\WorkCommand::runWorker
    vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php:86 Illuminate\Queue\Console\WorkCommand::handle
    [internal] call_user_func_array
    vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:32 Illuminate\Container\BoundMethod::Illuminate\Container\{closure}
    vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:90 Illuminate\Container\BoundMethod::callBoundMethod
    vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:34 Illuminate\Container\BoundMethod::call
    vendor/laravel/framework/src/Illuminate/Container/Container.php:576 Illuminate\Container\Container::call
    vendor/laravel/framework/src/Illuminate/Console/Command.php:183 Illuminate\Console\Command::execute
    vendor/symfony/console/Command/Command.php:255 Symfony\Component\Console\Command\Command::run
    vendor/laravel/framework/src/Illuminate/Console/Command.php:170 Illuminate\Console\Command::run
    vendor/symfony/console/Application.php:1000 Symfony\Component\Console\Application::doRunCommand
    vendor/symfony/console/Application.php:271 Symfony\Component\Console\Application::doRun
    vendor/symfony/console/Application.php:147 Symfony\Component\Console\Application::run
    vendor/laravel/framework/src/Illuminate/Console/Application.php:90 Illuminate\Console\Application::run
    vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:133 Illuminate\Foundation\Console\Kernel::handle
    artisan:37 [main]

**Comment by itsjeffro** [comment]
Oiiiii @paulycloud haha

It relates to a missing file from the vendor folder. Could you try doing the following

```
composer install
composer dump-autoload
```

**Comment by paulycloud** [comment]
Yes! Doing it now

**Comment by itsjeffro** [comment]
Im not sure if it relates to the issue, but there is a double foward slash there...

`/home/forge//releases/`

**Comment by paulycloud** [comment]
The "/home/forge//releases/" is there because I removed the site name :) 

/home/forge/"sitename"/releases/

**Comment by paulycloud** [comment]
Hi @itsjeffro 

Finally, got it working! For some reason, the only project that fails is the one we kept testing together. The others are able to connect to the server. 

There is a new error that I'll share but as for this one, consider it closed. 

Thanks for all your help.
