### ISSUE TITLE
Adding Auth Middleware to "/deploy"

### ISSUE THREAD

**Issue by paulycloud** [itsjeffro/deploy#32]
Hi @itsjeffro 

How can we add the "Auth" middleware or any middleware to the route for /Deploy? 

Thanks,

**Comment by itsjeffro** [comment]
Heya @paulycloud 

That can updated in config/deploy.php under middleware :)

Ill make sure i add that to the readme

**Comment by paulycloud** [comment]
Oh Sweet!!! Just made the update and it worked. Thanks!!
