### ISSUE TITLE
Cant select private github repos

### ISSUE THREAD

**Issue by itsjeffro** [itsjeffro/deploy#4]
Choosing a private github repo from the Add Project modal doesnt seem to work.

**Comment by robbfountain** [comment]
You need to add a scope of **repo** to your authorize URL.  Currently, you're defaulting to only public.

https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/

**Comment by itsjeffro** [comment]
Thanks, robbfountain. I'll update the scope as soon as I can.

Cheers

**Comment by itsjeffro** [comment]
Fixed in version v1.0.2
