### ISSUE TITLE
Feature Request: Store Servers list

### ISSUE THREAD

**Issue by paulycloud** [itsjeffro/deploy#41]
Hi @itsjeffro!!! 

So 1 week into the deployments, and everything is running smoothly!! Can't tell you how much I appreciate this. 👐

Regarding the processes of adding a new server for each new project, it would be great to have a page full section that has all my servers listed then when building a new project, i could either select from a dropdown menu or enter new server details. 

Small improvements like that will make the project creation flow much smoother.

**Comment by itsjeffro** [comment]
Good idea! I'll see if this is something i can add to version 1.

Otherwise, it might have to be a version 2 feature :)

**Comment by paulycloud** [comment]
Hi @itsjeffro 

What is the release date for version 2 :)

**Comment by itsjeffro** [comment]
Heya @paulycloud 

Hah, unfortunately there's no date. Ive just been trying to chip away at it when I get time.

**Comment by itsjeffro** [comment]
Added in v2.0.0
