### ISSUE TITLE
Documentation Update Request: FPM Reload Necessary for non-root users e.g. forge

### ISSUE THREAD

**Issue by paulycloud** [itsjeffro/deploy#42]
Hi @itsjeffro 

so i spent the last week trying to get my forge user to be able to reload FPM and I almost broke my server. Fortunately, I finally figured it out. :) 

With every deployment, there needs to be a step to reload FPM since a new sym link is created for the current folder. 

FPM by default can only be reloaded using the root user. To enable other users, especially the user selected when adding a new server, these permissions need to be granted in the /etc/sudoers file so that at the end of every deployment, this step can be added: 

**Name**: Reload FPM 
**Script**: 
cd {{ release }}
sudo service php7.4-fpm restart

Using "forge" as my connecting user, i am now able to reload FPM without requiring the root user access.

**Comment by itsjeffro** [comment]
Heya @paulycloud i believe this is already mentioned on the installation page http://deploy.itsjeffro.com/#/installation

Since it will vary depending on the ssh user and environment, I figured id leave this as generic as possible.

Happy to add the tip on adding to the sudoer file though.

**Comment by paulycloud** [comment]
Sweet. Just found it on the documentation! Thank you!
