### ISSUE TITLE
Symfony\Component\Debug\Exception\FatalThrowableErrorDeploy\Events\DeploymentDeploying

### ISSUE THREAD

**Issue by paulycloud** [itsjeffro/deploy#43]
Hey @itsjeffro 

So this is a weird one, this is only happening for 1 of my projects. The rest are fine. Here are the logs: 

Symfony\Component\Debug\Exception\FatalThrowableError Too few arguments to function Illuminate\Database\QueryException::__construct(), 0 passed in /home/forge/{{websitepath}}/releases/20200708034208/vendor/itsjeffro/deploy/src/Listeners/ProcessorErrorListener.php on line 41 and exactly 3 expected 
    vendor/laravel/framework/src/Illuminate/Database/QueryException.php:32 Illuminate\Database\QueryException::__construct
    vendor/itsjeffro/deploy/src/Listeners/ProcessorErrorListener.php:41 Deploy\Listeners\ProcessorErrorListener::handle
    [internal] call_user_func_array
    vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:366 Illuminate\Events\Dispatcher::Illuminate\Events\{closure}
    vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:196 Illuminate\Events\Dispatcher::dispatch
    vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:482 event
    vendor/itsjeffro/deploy/src/Processors/DeploymentProcessor.php:100 Deploy\Processors\DeploymentProcessor::fire
    vendor/itsjeffro/deploy/src/Jobs/DeployJob.php:53 Deploy\Jobs\DeployJob::handle
    [internal] call_user_func_array
    vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:32 Illuminate\Container\BoundMethod::Illuminate\Container\{closure}
    vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:90 Illuminate\Container\BoundMethod::callBoundMethod
    vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:34 Illuminate\Container\BoundMethod::call
    vendor/laravel/framework/src/Illuminate/Container/Container.php:576 Illuminate\Container\Container::call
    vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php:94 Illuminate\Bus\Dispatcher::Illuminate\Bus\{closure}
    vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:128 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:104 Illuminate\Pipeline\Pipeline::then
    vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php:98 Illuminate\Bus\Dispatcher::dispatchNow
    vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php:49 Illuminate\Queue\CallQueuedHandler::call
    vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php:88 Illuminate\Queue\Jobs\Job::fire
    vendor/laravel/framework/src/Illuminate/Queue/Worker.php:337 Illuminate\Queue\Worker::process
    vendor/laravel/framework/src/Illuminate/Queue/Worker.php:283 Illuminate\Queue\Worker::runJob
    vendor/laravel/framework/src/Illuminate/Queue/Worker.php:118 Illuminate\Queue\Worker::daemon
    vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php:102 Illuminate\Queue\Console\WorkCommand::runWorker
    vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php:86 Illuminate\Queue\Console\WorkCommand::handle
    [internal] call_user_func_array
    vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:32 Illuminate\Container\BoundMethod::Illuminate\Container\{closure}
    vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:90 Illuminate\Container\BoundMethod::callBoundMethod
    vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:34 Illuminate\Container\BoundMethod::call
    vendor/laravel/framework/src/Illuminate/Container/Container.php:576 Illuminate\Container\Container::call
    vendor/laravel/framework/src/Illuminate/Console/Command.php:183 Illuminate\Console\Command::execute
    vendor/symfony/console/Command/Command.php:255 Symfony\Component\Console\Command\Command::run
    vendor/laravel/framework/src/Illuminate/Console/Command.php:170 Illuminate\Console\Command::run
    vendor/symfony/console/Application.php:1000 Symfony\Component\Console\Application::doRunCommand
    vendor/symfony/console/Application.php:271 Symfony\Component\Console\Application::doRun
    vendor/symfony/console/Application.php:147 Symfony\Component\Console\Application::run
    vendor/laravel/framework/src/Illuminate/Console/Application.php:90 Illuminate\Console\Application::run
    vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:133 Illuminate\Foundation\Console\Kernel::handle
    artisan:37 [main]

**Comment by itsjeffro** [comment]
Heya @paulycloud 

Would be able to recall the steps you took prior to this happening. Ill have try and reproduce it.

Also, does any of the table data for this project look any different from the others?

**Comment by paulycloud** [comment]
Oi Mate @itsjeffro 😄

Any chance we could have another video call today? I'll send an invite out. Totally fine if you can't make it. I know its short notice.

**Comment by itsjeffro** [comment]
Yeah, pretty short notice :)

**Comment by paulycloud** [comment]
I figured out what's going on!!! Crazy stuff. I'd have to show you!

**Comment by itsjeffro** [comment]
Heya @paulycloud good work finding the issue. 

Ill be unavailable during the weekend. Any chance you could summarize if it was a data issue or a code issue?
