### ISSUE TITLE
404 Error on documentation

### ISSUE THREAD

**Issue by paulycloud** [itsjeffro/deploy#54]
Hi Jeffrey! 

Something's up with your documentation server. Getting a 404 error: 

http://deploy.itsjeffro.com/#/installation

**Comment by itsjeffro** [comment]
Hi @paulycloud 

Sorry for the late reply, I didn't get any notifications for this Github issue.

The site is currently down, but you can refer to the docs here https://github.com/itsjeffro/deploy-docs/tree/master/1.0

If this is in regards to upgrading from 1.x to 2.x, then please refer to https://github.com/itsjeffro/deploy/blob/master/UPGRADE.md. Please make sure you back up your db and ssh keys in the app directory before upgrading.

Clear application cache if you've used any route, config cache console command.
